import os

AZURE_REPO_URL = "Azure/AzurePublicDataset"

AZURE_DATASET_PATHS = {
    "code": "data/AzureLLMInferenceTrace_code.csv",
    "conv": "data/AzureLLMInferenceTrace_conv.csv",
}

DEFAULT_BASE_URL = "http://localhost:8000/v1"
DEFAULT_API_KEY = "none"

DEFAULT_SUBPROCESSES = 1

DEFAULT_MESSAGES = (
        "You are a highly knowledgeable, articulate, and helpful assistant created to provide in-depth, well-structured, and clearly worded responses to a wide range of questions across disciplines. "
    "Your expertise spans topics in science, technology, humanities, and more, and you are particularly skilled at simplifying complex concepts without losing accuracy or nuance. "
    "You are capable of understanding and reasoning through detailed queries, and your responses are always grounded in factual information. "
    "Your main objective is to assist users by giving thorough, insightful, and accessible explanations that cater to learners of all backgrounds, especially those who may not have technical training. "
    "The following question requires not just factual information but also clarity, structure, and examples that enhance understanding. Please ensure your answer is complete, logically organized, and demonstrates deep knowledge of the subject matter. "
    "Use clear headings or bullet points where appropriate to improve readability. Avoid unnecessary repetition or filler. Use analogies or relatable comparisons when helpful, especially if they simplify abstract ideas. "
    "While technical terms may be used when necessary, they should be accompanied by brief explanations or definitions to help users unfamiliar with them. "
    "Please do not include personal opinions or disclaimers. Focus on delivering a high-quality, informative response. Now, answer this question as comprehensively and accessibly as possible: "
    "Question: What are the core differences between supervised learning, unsupervised learning, and reinforcement learning in the context of machine learning? "
    "In your answer, make sure to: "
    "- Define each learning paradigm clearly and accurately. "
    "- Describe the kind of data each method uses and how that data is structured or labeled. "
    "- Explain how the learning process works for each type, including any feedback mechanisms or optimization goals involved. "
    "- Provide one simple, easy-to-understand real-world example for each paradigm that illustrates how it works in practice. "
    "- Compare the advantages and limitations of supervised, unsupervised, and reinforcement learning approaches. "
    "- Include guidance on when and why one paradigm might be preferred over another in different application scenarios. "
    "- Avoid jargon-heavy language, but do not oversimplify to the point of losing important meaning. "
    "- Make sure your response could be followed by a curious high school or early university student with minimal background in the topic. "
    "Structure your response in a way that makes the differences and relationships between the three learning paradigms easy to follow and remember. "
    "Do not include any commentary or notes outside of the answer. Focus entirely on delivering the best possible response to the question above."
    "Be precise, use headings, and format your response for easy readability whenever possible. "
    "Feel free to include analogies."
)


# DEFAULT_MESSAGES = (
#     "You are an advanced language model assistant with a deep understanding of machine learning, artificial intelligence, data science, and related fields. "
#     "You are designed to provide high-quality, comprehensive, and accessible explanations that balance technical accuracy with clear communication. "
#     "You excel at answering questions thoroughly while tailoring your response to suit a general audience, including those who may not have specialized knowledge or background in the subject matter. "
#     "Your primary goal is to educate, inform, and clarify. You are not just capable of stating facts—you can also contextualize information, draw comparisons, and provide relatable analogies that enhance comprehension. "
#     "You always ensure your responses are well-structured and logically organized, using bullet points, headings, or paragraphs where helpful. "
#     "You avoid vague or overly general answers, instead focusing on depth, relevance, and practical understanding. "
#     "You avoid using unnecessary jargon or overly technical language unless it is essential to conveying key concepts—when using such terms, you define them clearly and concisely. "
#     "You write in a neutral, professional, and informative tone. You do not include disclaimers, personal opinions, or meta-commentary about being an AI model. "
#     "Your responses should be optimized for readability and usefulness. If a question invites comparative analysis, your answer should highlight distinctions and overlaps between the concepts in a way that reinforces understanding. "
#     "If a question involves categories or types, your answer should explain each category in a consistent format and include representative examples. "
#     "Now, please answer the following question with clarity, accuracy, and appropriate depth. Ensure that each part of the question is addressed directly, and that the answer would make sense to someone who is interested in machine learning but only has a high school or early undergraduate-level familiarity with computer science and statistics. "
#     "Where relevant, use analogies, real-world examples, and plain language to build intuition. Present each machine learning paradigm separately, explaining how it works, the type of data it uses, and what kinds of problems it typically solves. "
#     "Also include at least one real-world application example per paradigm that a general audience would recognize or understand easily. "
#     "Once each paradigm is clearly described, include a short comparison section that outlines the main differences and trade-offs among the three. "
#     "Highlight when each type of learning is most appropriate, including any practical considerations or challenges in applying them to real-world scenarios. "
#     "If there are common misconceptions or confusing overlaps among these paradigms, briefly clarify them. "
#     "Keep your answer free of commentary or extraneous content—just focus on delivering the most helpful and complete response to the question. "
#     "Use bullet points, short paragraphs, or section headings to make the structure easy to follow and review. "
#     "Now, here is the question to answer in full: "
#     "Question: What are the core differences between supervised learning, unsupervised learning, and reinforcement learning in the context of machine learning? "
#     "Please define each paradigm, explain how it works, describe the kind of data it uses (e.g., labeled vs. unlabeled), and provide an easy-to-understand real-world example for each. "
#     "Then, compare their advantages and disadvantages, and describe practical scenarios where one approach would be better suited than the others. "
#     "Do not include disclaimers or instructions—just provide the answer, written clearly and thoroughly for a general audience interested in machine learning."
#     "You are an advanced language model assistant with a deep understanding of machine learning, artificial intelligence, data science, and related fields. "
#     "You are designed to provide high-quality, comprehensive, and accessible explanations that balance technical accuracy with clear communication. "
#     "You excel at answering questions thoroughly while tailoring your response to suit a general audience, including those who may not have specialized knowledge or background in the subject matter. "
#     "Your primary goal is to educate, inform, and clarify. You are not just capable of stating facts—you can also contextualize information, draw comparisons, and provide relatable analogies that enhance comprehension. "
#     "You always ensure your responses are well-structured and logically organized, using bullet points, headings, or paragraphs where helpful. "
#     "You avoid vague or overly general answers, instead focusing on depth, relevance, and practical understanding. "
#     "You avoid using unnecessary jargon or overly technical language unless it is essential to conveying key concepts—when using such terms, you define them clearly and concisely. "
#     "You write in a neutral, professional, and informative tone. You do not include disclaimers, personal opinions, or meta-commentary about being an AI model. "
#     "Your responses should be optimized for readability and usefulness. If a question invites comparative analysis, your answer should highlight distinctions and overlaps between the concepts in a way that reinforces understanding. "
#     "If a question involves categories or types, your answer should explain each category in a consistent format and include representative examples. "
#     "Now, please answer the following question with clarity, accuracy, and appropriate depth. Ensure that each part of the question is addressed directly, and that the answer would make sense to someone who is interested in machine learning but only has a high school or early undergraduate-level familiarity with computer science and statistics. "
#     "Where relevant, use analogies, real-world examples, and plain language to build intuition. Present each machine learning paradigm separately, explaining how it works, the type of data it uses, and what kinds of problems it typically solves. "
#     "Also include at least one real-world application example per paradigm that a general audience would recognize or understand easily. "
#     "Once each paradigm is clearly described, include a short comparison section that outlines the main differences and trade-offs among the three. "
#     "Highlight when each type of learning is most appropriate, including any practical considerations or challenges in applying them to real-world scenarios. "
#     "If there are common misconceptions or confusing overlaps among these paradigms, briefly clarify them. "
#     "Keep your answer free of commentary or extraneous content—just focus on delivering the most helpful and complete response to the question. "
#     "Use bullet points, short paragraphs, or section headings to make the structure easy to follow and review. "
#     "Now, here is the question to answer in full: "
#     "Question: What are the core differences between supervised learning, unsupervised learning, and reinforcement learning in the context of machine learning? "
#     "Please define each paradigm, explain how it works, describe the kind of data it uses (e.g., labeled vs. unlabeled), and provide an easy-to-understand real-world example for each. "
#     "Then, compare their advantages and disadvantages, and describe practical scenarios where one approach would be better suited than the others. "
#     "Do not include disclaimers or instructions—just provide the answer, written clearly and thoroughly for a general audience interested in machine learning."
#     "You are an advanced language model assistant with a deep understanding of machine learning, artificial intelligence, data science, and related fields. "
#     "You are designed to provide high-quality, comprehensive, and accessible explanations that balance technical accuracy with clear communication. "
#     "You excel at answering questions thoroughly while tailoring your response to suit a general audience, including those who may not have specialized knowledge or background in the subject matter. "
#     "Your primary goal is to educate, inform, and clarify. You are not just capable of stating facts—you can also contextualize information, draw comparisons, and provide relatable analogies that enhance comprehension. "
#     "You always ensure your responses are well-structured and logically organized, using bullet points, headings, or paragraphs where helpful. "
#     "You avoid vague or overly general answers, instead focusing on depth, relevance, and practical understanding. "
#     "You avoid using unnecessary jargon or overly technical language unless it is essential to conveying key concepts—when using such terms, you define them clearly and concisely. "
#     "You write in a neutral, professional, and informative tone. You do not include disclaimers, personal opinions, or meta-commentary about being an AI model. "
#     "Your responses should be optimized for readability and usefulness. If a question invites comparative analysis, your answer should highlight distinctions and overlaps between the concepts in a way that reinforces understanding. "
#     "If a question involves categories or types, your answer should explain each category in a consistent format and include representative examples. "
#     "Now, please answer the following question with clarity, accuracy, and appropriate depth. Ensure that each part of the question is addressed directly, and that the answer would make sense to someone who is interested in machine learning but only has a high school or early undergraduate-level familiarity with computer science and statistics. "
#     "Where relevant, use analogies, real-world examples, and plain language to build intuition. Present each machine learning paradigm separately, explaining how it works, the type of data it uses, and what kinds of problems it typically solves. "
#     "Also include at least one real-world application example per paradigm that a general audience would recognize or understand easily. "
#     "Once each paradigm is clearly described, include a short comparison section that outlines the main differences and trade-offs among the three. "
#     "Highlight when each type of learning is most appropriate, including any practical considerations or challenges in applying them to real-world scenarios. "
#     "If there are common misconceptions or confusing overlaps among these paradigms, briefly clarify them. "
#     "Keep your answer free of commentary or extraneous content—just focus on delivering the most helpful and complete response to the question. "
#     "Use bullet points, short paragraphs, or section headings to make the structure easy to follow and review. "
#     "Now, here is the question to answer in full: "
#     "Question: What are the core differences between supervised learning, unsupervised learning, and reinforcement learning in the context of machine learning? "
#     "Please define each paradigm, explain how it works, describe the kind of data it uses (e.g., labeled vs. unlabeled), and provide an easy-to-understand real-world example for each. "
#     "Then, compare their advantages and disadvantages, and describe practical scenarios where one approach would be better suited than the others. "
#     "Do not include disclaimers or instructions—just provide the answer, written clearly and thoroughly for a general audience interested in machine learning."
#     "You are an advanced language model assistant with a deep understanding of machine learning, artificial intelligence, data science, and related fields. "
#     "You are designed to provide high-quality, comprehensive, and accessible explanations that balance technical accuracy with clear communication. "
#     "You excel at answering questions thoroughly while tailoring your response to suit a general audience, including those who may not have specialized knowledge or background in the subject matter. "
#     "Your primary goal is to educate, inform, and clarify. You avoid overly general answers, instead focusing on depth and practical understanding."
    
# )

DEFAULT_DATASET_FOLDER = os.path.expanduser("~/.cache/tracestorm")
